# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/PYNQ-Z1_C.xdc

# Block Designs: bd/lab_3/lab_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3 || ORIG_REF_NAME==lab_3} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_processing_system7_0_0/lab_3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_processing_system7_0_0 || ORIG_REF_NAME==lab_3_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_axi_regmap_0_0/lab_3_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_axi_regmap_0_0 || ORIG_REF_NAME==lab_3_axi_regmap_0_0} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_ps7_0_axi_periph_0/lab_3_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_rst_ps7_0_100M_0/lab_3_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_xlslice_0_0/lab_3_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_xlslice_0_0 || ORIG_REF_NAME==lab_3_xlslice_0_0} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_xlslice_0_1/lab_3_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_xlslice_0_1 || ORIG_REF_NAME==lab_3_xlslice_0_1} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_multiplier_0_1/lab_3_multiplier_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_multiplier_0_1 || ORIG_REF_NAME==lab_3_multiplier_0_1} -quiet] -quiet

# IP: bd/lab_3/ip/lab_3_auto_pc_0/lab_3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab_3_auto_pc_0 || ORIG_REF_NAME==lab_3_auto_pc_0} -quiet] -quiet

# XDC: bd/lab_3/lab_3_ooc.xdc
