# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring 2023/ECE 1195/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_processing_system7_0_0/Lab_1_processing_system7_0_0.xci
# IP: The module: 'Lab_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring 2023/ECE 1195/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_processing_system7_0_0/Lab_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring 2023/ECE 1195/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_processing_system7_0_0/Lab_1_processing_system7_0_0.xci
# IP: The module: 'Lab_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring 2023/ECE 1195/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_processing_system7_0_0/Lab_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
