# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab_1/Lab_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1 || ORIG_REF_NAME==Lab_1} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_processing_system7_0_0/Lab_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_processing_system7_0_0 || ORIG_REF_NAME==Lab_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_axi_regmap_0_1/Lab_1_axi_regmap_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_axi_regmap_0_1 || ORIG_REF_NAME==Lab_1_axi_regmap_0_1} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_ps7_0_axi_periph_1/Lab_1_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==Lab_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_rst_ps7_0_100M_1/Lab_1_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==Lab_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_adder_0_1/Lab_1_adder_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_adder_0_1 || ORIG_REF_NAME==Lab_1_adder_0_1} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_ila_0_1/Lab_1_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_ila_0_1 || ORIG_REF_NAME==Lab_1_ila_0_1} -quiet] -quiet

# IP: bd/Lab_1/ip/Lab_1_auto_pc_0/Lab_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_1_auto_pc_0 || ORIG_REF_NAME==Lab_1_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab_1/Lab_1_ooc.xdc
