# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_auto_pc_0/Lab_2_auto_pc_0.xci
# IP: The module: 'Lab_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_auto_pc_0/Lab_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_auto_pc_0/Lab_2_auto_pc_0.xci
# IP: The module: 'Lab_2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/Lab_2/Lab_2.srcs/sources_1/bd/Lab_2/ip/Lab_2_auto_pc_0/Lab_2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
