# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/system_PL2PS_AXI_0.xci
# IP: The module: 'system_PL2PS_AXI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/bd_3808.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_0/bd_3808_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_1/bd_3808_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_2/bd_3808_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_3/bd_3808_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_4/bd_3808_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_5/bd_3808_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_6/bd_3808_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_7/bd_3808_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_8/bd_3808_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_9/bd_3808_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_10/bd_3808_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_11/bd_3808_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_12/bd_3808_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_1/bd_3808_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_1/bd_3808_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_5/bd_3808_s00a2s_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_6/bd_3808_sarn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_7/bd_3808_srn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_8/bd_3808_sawn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_9/bd_3808_swn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_10/bd_3808_sbn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_11/bd_3808_m00s2a_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PL2PS_AXI_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/system_PL2PS_AXI_0.xci
# IP: The module: 'system_PL2PS_AXI_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/bd_3808.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_0/bd_3808_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_1/bd_3808_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_2/bd_3808_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_3/bd_3808_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_4/bd_3808_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_5/bd_3808_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_6/bd_3808_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_7/bd_3808_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_8/bd_3808_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_9/bd_3808_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_10/bd_3808_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_11/bd_3808_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_12/bd_3808_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_1/bd_3808_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_1/bd_3808_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_5/bd_3808_s00a2s_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_6/bd_3808_sarn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_7/bd_3808_srn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_8/bd_3808_sawn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_9/bd_3808_swn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_10/bd_3808_sbn_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/bd_0/ip/ip_11/bd_3808_m00s2a_0_ooc.xdc

# XDC: c:/Users/pacel/Documents/Spring_2023/ECE_1195/lab_6/vivado/lab6/lab6.srcs/sources_1/bd/system/ip/system_PL2PS_AXI_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_PL2PS_AXI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
