@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 22 13:48:19 -0400 2023
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim CPU_mem_wrapper_behav -key {Behavioral:sim_1:Functional:CPU_mem_wrapper} -tclbatch CPU_mem_wrapper.tcl -protoinst "protoinst_files/CPU_mips.protoinst" -protoinst "protoinst_files/CPU_mem.protoinst" -protoinst "protoinst_files/CPU_mips.protoinst" -protoinst "protoinst_files/CPU_TL.protoinst" -protoinst "protoinst_files/CPU_mips.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
