# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/PYNQ-Z1_C.xdc

# Block Designs: bd/CPU_TL/CPU_TL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL || ORIG_REF_NAME==CPU_TL} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_processing_system7_0_0/CPU_TL_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_processing_system7_0_0 || ORIG_REF_NAME==CPU_TL_processing_system7_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_axi_regmap_0_0/CPU_TL_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_axi_regmap_0_0 || ORIG_REF_NAME==CPU_TL_axi_regmap_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_ps7_0_axi_periph_0/CPU_TL_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_ps7_0_axi_periph_0 || ORIG_REF_NAME==CPU_TL_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_rst_ps7_0_100M_0/CPU_TL_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_rst_ps7_0_100M_0 || ORIG_REF_NAME==CPU_TL_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_CPU_mips_wrapper_0_0/CPU_TL_CPU_mips_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_CPU_mips_wrapper_0_0 || ORIG_REF_NAME==CPU_TL_CPU_mips_wrapper_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_blk_mem_gen_0_0/CPU_TL_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_blk_mem_gen_0_0 || ORIG_REF_NAME==CPU_TL_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_xlconcat_0_0/CPU_TL_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_xlconcat_0_0 || ORIG_REF_NAME==CPU_TL_xlconcat_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_xlconstant_0_0/CPU_TL_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_xlconstant_0_0 || ORIG_REF_NAME==CPU_TL_xlconstant_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_axi_bram_ctrl_0_0/CPU_TL_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_axi_bram_ctrl_0_0 || ORIG_REF_NAME==CPU_TL_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_xbar_0/CPU_TL_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_xbar_0 || ORIG_REF_NAME==CPU_TL_xbar_0} -quiet] -quiet

# IP: bd/CPU_TL/ip/CPU_TL_auto_pc_0/CPU_TL_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_TL_auto_pc_0 || ORIG_REF_NAME==CPU_TL_auto_pc_0} -quiet] -quiet

# XDC: bd/CPU_TL/CPU_TL_ooc.xdc
