# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_AXI_DMA_0/system_AXI_DMA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_DMA_0 || ORIG_REF_NAME==system_AXI_DMA_0} -quiet] -quiet

# IP: bd/system/ip/system_IRQ_CONCAT_0/system_IRQ_CONCAT_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_IRQ_CONCAT_0 || ORIG_REF_NAME==system_IRQ_CONCAT_0} -quiet] -quiet

# IP: bd/system/ip/system_PL2PS_AXI_0/system_PL2PS_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PL2PS_AXI_0 || ORIG_REF_NAME==system_PL2PS_AXI_0} -quiet] -quiet

# IP: bd/system/ip/system_PS2PL_AXI_0/system_PS2PL_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PS2PL_AXI_0 || ORIG_REF_NAME==system_PS2PL_AXI_0} -quiet] -quiet

# IP: bd/system/ip/system_PS7_0/system_PS7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PS7_0 || ORIG_REF_NAME==system_PS7_0} -quiet] -quiet

# IP: bd/system/ip/system_PSR_0/system_PSR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PSR_0 || ORIG_REF_NAME==system_PSR_0} -quiet] -quiet

# IP: bd/system/ip/system_hw_conv_0_0/system_hw_conv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hw_conv_0_0 || ORIG_REF_NAME==system_hw_conv_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
