# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pacel/Desktop/Work/Pitt/semesters/Spring_2023/ECE_1195/PYNQ-Z1_C.xdc

# Block Designs: bd/Lab_2/Lab_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2 || ORIG_REF_NAME==Lab_2} -quiet] -quiet

# IP: bd/Lab_2/ip/Lab_2_axi_regmap_0_0/Lab_2_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_axi_regmap_0_0 || ORIG_REF_NAME==Lab_2_axi_regmap_0_0} -quiet] -quiet

# IP: bd/Lab_2/ip/Lab_2_ALU_0_0/Lab_2_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_ALU_0_0 || ORIG_REF_NAME==Lab_2_ALU_0_0} -quiet] -quiet

# IP: bd/Lab_2/ip/Lab_2_processing_system7_0_0/Lab_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_processing_system7_0_0 || ORIG_REF_NAME==Lab_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_2/ip/Lab_2_ps7_0_axi_periph_0/Lab_2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab_2/ip/Lab_2_rst_ps7_0_100M_0/Lab_2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab_2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab_2/ip/Lab_2_auto_pc_0/Lab_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_2_auto_pc_0 || ORIG_REF_NAME==Lab_2_auto_pc_0} -quiet] -quiet

# XDC: bd/Lab_2/Lab_2_ooc.xdc
