webtalk_init -webtalk_dir c:/users/pacel/desktop/work/pitt/semesters/spring_2023/ece_1195/lab_1/lab_1.tmp/adder_v1_0_project/adder_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 29 23:58:47 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9d3dbf78-e2cc-48ad-a216-2cae9a3035af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "69c2324819494f1c8878d9e2a129ae5c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7848_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1060712174 -regid "" -xml c:/users/pacel/desktop/work/pitt/semesters/spring_2023/ece_1195/lab_1/lab_1.tmp/adder_v1_0_project/adder_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html c:/users/pacel/desktop/work/pitt/semesters/spring_2023/ece_1195/lab_1/lab_1.tmp/adder_v1_0_project/adder_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm c:/users/pacel/desktop/work/pitt/semesters/spring_2023/ece_1195/lab_1/lab_1.tmp/adder_v1_0_project/adder_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
